services:
  cloudflared:  # Nombre del servicio
    image: cloudflare/cloudflared:latest  # Imagen oficial de Cloudflare Tunnel
    container_name: cloudflared  # Nombre personalizado del contenedor
    restart: unless-stopped  # Se reinicia automáticamente si falla o al reiniciar el servidor

    security_opt:
      - no-new-privileges:true  # Evita que el contenedor escale privilegios

    environment:
      - TZ=America/El_Salvador  # Zona horaria del contenedor
      - TUNNEL_TOKEN=  # Token generado en Cloudflare Zero Trust

    command: tunnel --no-autoupdate run  # Ejecuta el túnel y desactiva auto-actualización interna
