services:
  filebrowser:  # Nombre del servicio
    image: hurlenko/filebrowser:v2.23.0  # Imagen específica
    container_name: filebrowser  # Nombre personalizado del contenedor
    restart: unless-stopped  # Se reinicia automáticamente si falla o reinicia el servidor

    security_opt:
      - no-new-privileges:true  # Impide que el contenedor obtenga privilegios adicionales

    environment:
      - UID=1000  # Usuario que ejecuta el servicio dentro del contenedor
      - GID=1000  # Grupo asociado
      - TZ=America/El_Salvador  # Zona horaria para logs correctos

    volumes:
      - /etc/localtime:/etc/localtime:ro  # Sincroniza hora del host
      - /datos:/data  # Carpeta principal que se podrá explorar desde el navegador
      - /datos/filebrowser/config:/config  # Base de datos y configuración interna

    ports:
      - "1000:8080"  # Acceso web → http://IP_DEL_SERVIDOR:1000
