services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped

    environment:
      - PUID=33
      - PGID=33
      - TZ=America/El_Salvador
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /datos/qbittorrent/appdata:/config
      - /datos/descargas:/downloads
    
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
